# Generated by Django 5.2.6 on 2025-09-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_xrayanalysis_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xrayanalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'X-ray Analysis', 'verbose_name_plural': 'X-ray Analyses'},
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
